name: build-and-push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Docker Image Tag
      id: set-tag
      run: |
        export TAG="release-$(date +%Y%m%d%H%M%S)"
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT
        echo "$TAG" > image_tag.txt

    - name: Build Docker Image
      run: docker build -t ghcr.io/your-org/your-image:${{ steps.set-tag.outputs.image_tag }} .

    - name: Push Docker Image
      run: docker push ghcr.io/your-org/your-image:${{ steps.set-tag.outputs.image_tag }}

    - name: Upload Tag Artifact
      uses: actions/upload-artifact@v3
      with:
        name: image-tag
        path: image_tag.txt
