apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        # Vault annotations for injecting secrets

        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "web-role"
        vault.hashicorp.com/agent-inject-secret-DATABASE_NAME: "kv/data/Kubernetes/Postgres-Database"
        vault.hashicorp.com/agent-inject-template-DATABASE_NAME: |
          {{- with secret "kv/data/Kubernetes/Postgres-Database" -}}
          export DATABASE_NAME="{{ .Data.data.DATABASE_NAME }}"
          {{- end }}

        #
    spec:
      serviceAccountName: web-sa
      containers:
      - name: web-container
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
      #   volumeMounts:
      #   - name: html-volume
      #     mountPath: /usr/share/nginx/html
      # volumes:
      # - name: html-volume
      #   configMap:
      #     name: web-html-config