name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - main
          - dev
          - qa
          # - uat
          # - cug
          # - prod
          # - dr
  push:
    branches:
      - main
      - dev
      - qa
      # - uat
      # - cug
      # - prod
      # - dr
  pull_request:
    branches:
      - main
      - dev
      - qa
      # - uat
      # - cug
      # - prod
      # - dr

env:
  REGISTRY: docker.io
  # REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up REGISTRY and ENV vars
        run: |
          echo "REGISTRY=${{ secrets.ACR_NAME }}.azurecr.io" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment || github.ref_name }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Docker Login to ACR
      #   run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ${REGISTRY}/${IMAGE_NAME}:${GITHUB_RUN_NUMBER}
      #       ${REGISTRY}/${IMAGE_NAME}:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
        # run: |
        #   docker build -t ${REGISTRY}/${IMAGE_NAME}:${inputs.environment}-${GITHUB_RUN_NUMBER} .
        #   # docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest
        run: |
          docker build -t ${REGISTRY}/${IMAGE_NAME}:${inputs.environment}-${GITHUB_RUN_NUMBER} .
